In [48]:
import pandas as pd
import numpy as np
import json 
import re

In [49]:
path = 'data_adidas_2.json'
df = pd.read_json(path)
df.sample(3)

,availability,avg_rating,brand,color,currency,description,images,name,price,original_price,review_count,scraped_at,url,category,cloth_gender
597,InStock,NaN,adidas,Night Indigo,USA,THIS LOOSE-FIT WINDBREAKER IS MADE IN PART WIT...,"[https://assets.adidas.com/images/w_600,f_auto...",ADICOLOR TREFOIL WINDBREAKER,$100,$100,0,2023-12-11 09:15:25,https://www.adidas.com/us/adicolor-trefoil-win...,Clothing,Men
730,InStock,NaN,adidas,Black,USA,EVERYDAY SHORTS MADE WITH A BLEND OF RECYCLED ...,"[https://assets.adidas.com/images/w_600,f_auto...",Z.N.E. PREMIUM SHORTS,$65,$65,61,2023-12-11 11:36:23,https://www.adidas.com/us/z.n.e.-premium-short...,Clothing,Men
286,OutOfStock,NaN,adidas,Olive Strata S23,USA,AN EVERYDAY HOODIE MADE WITH A BLEND OF RECYCL...,"[https://assets.adidas.com/images/w_600,f_auto...",ESSENTIALS FLEECE 3-STRIPES FULL-ZIP HOODIE,$30,$65,0,2023-12-11 06:07:21,https://www.adidas.com/us/essentials-fleece-3-...,Clothing,Men

In [50]:
# Thay thế các dấu /n trong description
descrip =  []
for index,item in enumerate(df.description):
    try:
        descrip.append(re.sub("\n"," ",item))
    except:
        descrip.append(item)

len(descrip)

919

In [51]:
df.description = descrip
df.sample(2)

,availability,avg_rating,brand,color,currency,description,images,name,price,original_price,review_count,scraped_at,url,category,cloth_gender
629,InStock,4.5,adidas,Pulse Olive,USA,WATERPROOF SKI PANTS MADE IN PART WITH RECYCLE...,"[https://assets.adidas.com/images/w_600,f_auto...",TERREX 3-LAYER POST-CONSUMER NYLON SNOW PANTS,$400,$400,4,2023-12-11 09:51:11,https://www.adidas.com/us/terrex-3-layer-post-...,Clothing,Men
238,InStock,NaN,adidas,None,USA,A Y-3 TEE THAT PLAYS WITH THE CLASSIC 3-STRIPE...,"[https://assets.adidas.com/images/w_600,f_auto...",None,$200,$200,2,2023-12-11 05:54:35,https://www.adidas.com/us/y-3-3-stripes-short-...,Clothing,Y-3

In [52]:
price =  []
for index,item in enumerate(df.price):
    try:
        price.append(int(re.sub(r'\D', '', item)))
    except:
        price.append(item)

df.price = price
len(price)

919

In [53]:
df.sample(2)

,availability,avg_rating,brand,color,currency,description,images,name,price,original_price,review_count,scraped_at,url,category,cloth_gender
421,OutOfStock,NaN,adidas,Arctic Fusion,USA,A COZY HOODIE MADE WITH A BLEND OF RECYCLED AN...,"[https://assets.adidas.com/images/w_600,f_auto...",ALL SZN GARMENT-WASH HOODIE,30,$65,0,2023-12-11 06:56:45,https://www.adidas.com/us/all-szn-garment-wash...,Clothing,Men
769,InStock,NaN,adidas,Black / White,USA,VERSATILE TRAINING SHORTS MADE WITH RECYCLED M...,"[https://assets.adidas.com/images/w_600,f_auto...",TRAIN ESSENTIALS LOGO TRAINING SHORTS,14,$35,61,2023-12-11 12:01:22,https://www.adidas.com/us/train-essentials-log...,Clothing,Men

In [54]:
origin_price =  []
for index,item in enumerate(df.original_price):
    try:
        origin_price.append(int(re.sub(r'\D', '', item)))
    except:
        origin_price.append(item)

df.original_price = origin_price

In [55]:
df.sample(2)

,availability,avg_rating,brand,color,currency,description,images,name,price,original_price,review_count,scraped_at,url,category,cloth_gender
234,InStock,3.9,adidas,Silver Pebble S23 / White,USA,"A MOISTURE-ABSORBING T-SHIRT, MADE IN PART WIT...","[https://assets.adidas.com/images/w_600,f_auto...",TRAIN ICONS SMALL LOGO LONG SLEEVE TRAINING TEE,35,50,16,2023-12-11 05:53:11,https://www.adidas.com/us/train-icons-small-lo...,Clothing,Men
733,InStock,NaN,adidas,Black,USA,COMFORTABLE SHORTS WITH ANIMAL STRIPES. Style ...,"[https://assets.adidas.com/images/w_600,f_auto...",GRAPHICS ANIMAL SHORTS,65,65,0,2023-12-11 11:36:48,https://www.adidas.com/us/graphics-animal-shor...,Clothing,Men

In [56]:
df.dtypes

availability              object
avg_rating               float64
brand                     object
color                     object
currency                  object
description               object
images                    object
name                      object
price                      int64
original_price             int64
review_count               int64
scraped_at        datetime64[ns]
url                       object
category                  object
cloth_gender              object
dtype: object

In [57]:
df.to_csv('data_crawl.csv')